require 'rspec-puppet/matchers/create_generic'
require 'rspec-puppet/matchers/create_resource'
require 'rspec-puppet/matchers/include_class'
require 'rspec-puppet/matchers/include_all_deps'
require 'rspec-puppet/matchers/run'
