inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - spec/fixtures/**/*
    - vendor/bundle/**/*
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: '2.7'

# Disabled
Style/ClassAndModuleChildren:
  Enabled: false

####################################################
# Cops below here due for deprecation
####################################################
# ``Rspec/FilePath`` is going to be deprecated in the next major release of rubocop >=3.0.0: see <https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FilePath>
# As the new cops are already present, e.g., Rspec/SpecFilePathPathFormat, then disabling this in preparation
RSpec/FilePath:
  Enabled: false