build: off

branches:
  only:
    - master

# ruby versions under test
environment:
  matrix:
    - RUBY_VERSION: 23-x64
      PUPPET_GEM_VERSION: '~> 4.8.0'
    - RUBY_VERSION: 21
      PUPPET_GEM_VERSION: '~> 4.8.0'
    - RUBY_VERSION: 193
      PUPPET_GEM_VERSION: '~> 4.8.0' 
    - RUBY_VERSION: 23-x64
      PUPPET_GEM_VERSION: '~> 4.7.0'
    - RUBY_VERSION: 21
      PUPPET_GEM_VERSION: '~> 4.7.0'
    - RUBY_VERSION: 193
      PUPPET_GEM_VERSION: '~> 4.7.0'
    - RUBY_VERSION: 23-x64
      PUPPET_GEM_VERSION: '~> 4.5.0'
    - RUBY_VERSION: 21
      PUPPET_GEM_VERSION: '~> 4.5.0'
    - RUBY_VERSION: 193
      PUPPET_GEM_VERSION: '~> 4.5.0'
    - RUBY_VERSION: 23-x64
      PUPPET_GEM_VERSION: '~> 4.4.0'
    - RUBY_VERSION: 21
      PUPPET_GEM_VERSION: '~> 4.4.0'
    - RUBY_VERSION: 193
      PUPPET_GEM_VERSION: '~> 4.4.0'
    - RUBY_VERSION: 23-x64
      PUPPET_GEM_VERSION: '~> 4.3.0'
    - RUBY_VERSION: 21
      PUPPET_GEM_VERSION: '~> 4.3.0'
    - RUBY_VERSION: 193
      PUPPET_GEM_VERSION: '~> 4.3.0'
    - RUBY_VERSION: 23-x64
      PUPPET_GEM_VERSION: '~> 4.2.0'
    - RUBY_VERSION: 21
      PUPPET_GEM_VERSION: '~> 4.2.0'
    - RUBY_VERSION: 193
      PUPPET_GEM_VERSION: '~> 4.2.0'
    # Latest gem release
    - RUBY_VERSION: 23-x64
      PUPPET_GEM_VERSION: '~> 4.0'
    # Latest code from puppetlabs/puppet.git
    - RUBY_VERSION: 23-x64
      PUPPET_GEM_VERSION: 'https://github.com/puppetlabs/puppet.git#master'
    - RUBY_VERSION: 23-x64
      PUPPET_GEM_VERSION: 'https://github.com/puppetlabs/puppet.git#stable'

matrix:
  allow_failures:
    # Don't fail for puppet.git#master because it may be to blame for any failures
    - PUPPET_GEM_VERSION: 'https://github.com/puppetlabs/puppet.git#master'

install:
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - SET LOG_SPEC_ORDER=true
  - ruby -v
  - gem -v
  - bundle -v
  - bundle install --jobs 4 --retry 2 --without development

before_test:
  - type Gemfile.lock

test_script:
  - bundle exec rake test

notifications:
  email:
    - tim@bombasticmonkey.com
